package gui.html;

public class CadastrarPratoHTML {

  String html = "<!doctype html>\n"
      + "<html lang=\"pt-br\">\n"
      + "  <head>\n"
      + "    <!-- Required meta tags -->\n"
      + "    <meta charset=\"utf-8\">\n"
      + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
      + "\n"
      + "    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\">\n"
      + "    <style>\n"
      + "        .navbar {\n"
      + "  color: #c51919;\n"
      + "  background-color: #e9c4de;\n"
      + "}\n"
      + "\n"
      + ".nav-link {\n"
      + "  color: #c51919;\n"
      + "}\n"
      + "\n"
      + ".card-title {\n"
      + "  color: #c51919;\n"
      + "}\n"
      + "\n"
      + ".nav {\n"
      + "  color: #FFFFFF;\n"
      + "  background-color: #CC3333;\n"
      + "}\n"
      + "\n"
      + ".card {\n"
      + "  background: #f0dfec;\n"
      + "}\n"
      + "    </style>\n"
      + "\n"
      + "    <!-- Optional JavaScript -->\n"
      + "    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n"
      + "    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n"
      + "    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\n"
      + "    <title>No Q</title>\n"
      + "  </head>\n"
      + "  <body>\n"
      + "    <nav class=\"navbar navbar-fixed-top navbar-expand-lg \">\n"
      + "        <div class=\"container\">\n"
      + "                \n"
      + "            <a class=\"navbar-brand h1 mb-0\" href=\"/home\">\n"
      + "                <img src=\"https://i.imgur.com/qG71wOq.png\" height=\"45\" width=\"70\" alt=\"\">\n"
      + "            </a>\n"
      + "            <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSite\">\n"
      + "                <span class=\"navbar-toggler-icon\"></span>\n"
      + "            </button>\n"
      + "            <div class=\"collapse navbar-collapse\" id=\"navbarSite\">\n"
      + "                <ul class=\"navbar-nav ml-auto\">\n"
      + "                    <li class=\"nav-item\">\n"
      + "                        <a class=\"navbar-brand h1 mb-0\" href=\"#\">\n"
      + "                            <img src=\"https://i.imgur.com/ABhNqvX.png\" height=\"40\" width=\"40\" alt=\"\">\n"
      + "                        </a>\n"
      + "                    </li>\n"
      + "                    <li class=\"nav-item\">\n"
      + "                            <a class=\"nav-link\" href=\"../../listar/prato\">Pratos</a>\n"
      + "                    </li>\n"
      + "                    <li class=\"nav-item\">\n"
      + "                            <a class=\"nav-link\" href=\"#\">Sair</a>\n"
      + "                    </li>\n"
      + "                </ul>\n"
      + "            </div>\n"
      + "        </div>\n"
      + "    </nav>\n"
      + "    <div class=\"container\"> <p></p></div>\n"
      + "        <div class=\"container\">\n"
      + "            <form method=\"post\" action=\"cadastrar/prato/\" id=\"formPrato\" name=\"formPrato\">\n"
      + "                <div class=\"form-row\">\n"
      + "                    <div class=\"form-group col-sm-9\">\n"
      + "                        <input type=\"text\" class=\"form-control\" name=\"inputNome\" id=\"inputNome\" placeholder=\"Nome do Prato\">\n"
      + "                    </div>\n"
      + "                </div>\n"
      + "                <div class=\"form-row\">\n"
      + "                    <div class=\"form-group col-sm-9\">\n"
      + "                        <textarea class=\"form-control\" rows=\"5\" name=\"inputDescricao\" id=\"inputDescricao\" placeholder=\"Descrição, ingredientes...\"></textarea>\n"
      + "                    </div>\n"
      + "                </div>\n"
      + "                <div class=\"form-row\">\n"
      + "                    <div class=\"form-group col-sm-4\">\n"
      + "                        <input type=\"number\" class=\"form-control\" name=\"inputTempo\" id=\"inputTempo\" placeholder=\"Tempo de Preparo em Minutos\">\n"
      + "                    </div>\n"
      + "                    <div class=\"form-group col-sm-4\">\n"
      + "                        <input type=\"text\" class=\"form-control\" name=\"inputReais\" id=\"inputReais\" placeholder=\"Preço\">\n"
      + "                    </div>\n"
      + "                    <div class=\"form-group col-sm-2\">\n"
      + "                        <input type=\"submit\" class=\"btn btn-danger form-control\" href=\"\" value=\"cadastrar\">Salvar</input>\n"
      + "                    </div>\n"
      + "                </div>\n"
      + "            </form>\n"
      + "        </div>\n"
      + "    </div>\n"
      + "\n"
      + "\n"
      + "    <!-- Optional JavaScript -->\n"
      + "    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n"
      + "    <script src=\"node_modules/jquery/dist/jquery.js\"></script>\n"
      + "    <script src=\"node_modules/popper.js/dist/umd/popper.js\"></script>\n"
      + "    <script src=\"node_modules/bootstrap/dist/js/bootstrap.js\"></script>\n"
      + "  </body>\n"
      + "</html>";

  public String getHtml() {
    return this.html;
  }

}
